### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by snoopspy** [bobbf/fbcrawler#1]
access-token이 expired되어서 제대로 된 응답을 받지 못하는 경우 access-token을 재발급받고 코드에 적용시켜야 한다. 이러한 현상 빨리 캐치해서 대응할 수 있도록 코드 레벨에서 알람을 줄 수 있도록 한다(행사장에서 실시간 대응을 할 수 있도록).

**Comment by citron0137** [comment]
69e3458e426f16f8b92b7497df915992d961c8fe
알람을 주는 기능은 구현했으나, 토큰을 클라이언트에서 가져오도록 하는 방법을 채택하려고 노력하고 있습니다.

**Comment by citron0137** [comment]
그 외의 400는 분석이 필요하므로 일단은 에러를 띄위고 다시 반복하도록 했습니다.
이를 마지막으로 이 이슈는 닫고 토큰 재발급 이슈를 생성하겠습니다
