### ISSUE TITLE
comment 크롤링 처리 개선

### ISSUE THREAD

**Issue by snoopspy** [bobbf/fbcrawler#2]
Like 수가 많은 것 위주로 보여 주게 되면, 댓글이 N개인 경우 계속해서 N개의 comment를 계속해서 긁어 와야 하는데, N이 계속해서 증가할 것이고 access-token의 소비가 많아 진다. 따라서 다음과 같이 처리한다.

1. 이미 긁어 온 comment에 대해서는 더 이상 긁어 오지 않도록 한다.
2. 이미 긁어 온 comment들은 프로그램이 loading될 때 특정 파일에서 리스트를 읽어 들이고 프로그램이 종료될 때 파일로 저장한다.
3. Like 수는 비콘으로 뿌릴 때 감안하지 않는다.

**Comment by citron0137** [comment]
69e3458e426f16f8b92b7497df915992d961c8fe
여기에서 처리 되었습니다.
쿼리 한번으로 댓글을 모두 가져오는 방식으로 처리했습니다.(1,2번 해결)
3번 like 수도 가져오지 않도록 했습니다.
